package(default_visibility = ["//visibility:public"])

cc_library(
  name = "quadtree",
  hdrs = ["quadtree.h"],
  srcs = ["quadtree.cpp",
        ],
  deps = ["//kern_interp:ki_mat",
      "//kern_interp/boundaries"]
)